import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const liberRegular = localFont({
  src: "../public/fonts/LiberRegular.woff",
  weight: "400",
  style: "normal",
  variable: "--font-liber",
});

const beautifullyDelicious = localFont({
  src: "../public/fonts/BDSans-Thin.woff",
  weight: "400",
  style: "normal",
  variable: "--font-beautifully-delicious",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${liberRegular.variable} ${beautifullyDelicious.variable} ${geistSans.variable} ${geistMono.variable} font-delicious font-medium antialiased text-black flex justify-center items-center`}
      >
        {children}
      </body>
    </html>
  );
}
