name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: 'code/portfolio-maria/portfolio-maria/package-lock.json'  # Ajuste aqui

      - name: Instalar dependências
        run: npm install
        working-directory: code/portfolio-maria/portfolio-maria  # Ajuste aqui

      - name: Construir o Next.js
        run: npm run build
        working-directory: code/portfolio-maria/portfolio-maria  # Ajuste aqui

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: code/portfolio-maria/portfolio-maria/out  # Ajuste aqui

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4